#!/usr/bin/env python3
"""Register a new image-generation provider for ppt-anything.

Writes ~/.ppt-anything/providers/<name>.toml from user-supplied fields, then
runs an end-to-end verification: generates one tiny image via the cheapest
available model. Only marks verified=true when the round-trip succeeds.

DESIGN:
  - Inputs are passed as flags (or piped via stdin) so the agent doesn't
    accidentally inline the api_key into a long shell command line.
  - Verification spends ~$0.04 on a Flash-tier 1024x576 image. Failure means
    the toml is left with verified=false and a non-zero exit so the caller
    can flag the user.
  - This is the agent's tool. The agent NEVER reads the toml directly. It
    invokes this script, which writes + verifies on its own.

USAGE:
  register-provider.py \\
    --name my-bridge \\
    --base-url https://example.com \\
    --auth-style bearer \\
    --docs-url https://example.com/docs \\
    --api-key 'sk-...'                 # or pipe via stdin with --key-stdin

  --no-verify          skip verification (writes toml only; not recommended)
  --force              overwrite existing toml of same name
  --models 'a,b,c'     override the default model list (must include a Flash
                       model for verification)
"""

from __future__ import annotations

import argparse
import os
import re
import subprocess
import sys
from datetime import date
from pathlib import Path

PROVIDER_DIR = Path.home() / ".ppt-anything" / "providers"
SCRIPT_DIR = Path(__file__).resolve().parent
GENERATE_IMAGE = SCRIPT_DIR / "generate-image.py"

DEFAULT_MODELS_GEMINI = [
    "gemini-3-pro-image-preview",
    "gemini-2.5-flash-image",
    "gemini-3.1-flash-image-preview",
]
VERIFY_MODEL = "gemini-2.5-flash-image"  # cheapest Gemini-shape Flash
VERIFY_PROMPT = "a small watercolor sketch of a single round red apple on white paper, minimal"

VALID_NAME_RE = re.compile(r"^[a-z0-9][a-z0-9._-]*$")


def die(msg: str, code: int = 1) -> None:
    print(f"error: {msg}", file=sys.stderr)
    sys.exit(code)


def render_toml(name: str, display: str, base_url: str, api_key: str,
                auth_style: str, docs_url: str, models: list[str]) -> str:
    model_lines = ",\n".join(f'    "{m}"' for m in models)
    return f"""# Auto-generated by register-provider.py.
# Edit fields below directly if needed; verified flag will reset to false on
# any field change you make manually if you want to re-verify.

[provider]
name = "{name}"
display_name = "{display}"
region = "global"
default = false
verified = false                        # set to true after successful round-trip
verified_date = ""

[auth]
api_key  = "{api_key}"
base_url = "{base_url}"
docs_url = "{docs_url}"
auth_style = "{auth_style}"             # "google" | "bearer"

[models]
default = "{models[0]}"
choices = [
{model_lines},
]

[defaults]
size = "2K"
aspect_ratio = "16:9"

[capabilities]
image_to_image = true
max_ref_size_mb = 10
multi_ref = true
billing_on_failure = true

[how_to_use]
invoke = "generate-image.py --provider {name} -m {{model}} --size {{size}} -r {{aspect_ratio}} --ref {{ref}} '{{prompt}}'"
notes = \"\"\"\\
Auto-registered. Verified at registration via {VERIFY_MODEL} round-trip.
If you change base_url / api_key / auth_style, re-run register-provider.py
or set [provider].verified back to false manually.
\"\"\"
"""


def mark_verified(toml_path: Path) -> None:
    text = toml_path.read_text()
    today = date.today().isoformat()
    text = text.replace('verified = false ', f'verified = true  ', 1)
    text = text.replace('verified_date = ""', f'verified_date = "{today}"', 1)
    toml_path.write_text(text)


def verify_round_trip(name: str) -> tuple[bool, str]:
    """Generate one image via this provider. Return (ok, message)."""
    out_dir = Path("/tmp") / f"register-verify-{name}"
    out_dir.mkdir(exist_ok=True)
    cmd = [
        sys.executable, str(GENERATE_IMAGE),
        "--provider", name,
        "-m", VERIFY_MODEL,
        "-r", "16:9",
        "-n", "verify",
        "-o", str(out_dir),
        "--no-preview",
        "--timeout", "120",
        VERIFY_PROMPT,
    ]
    try:
        result = subprocess.run(cmd, capture_output=True, text=True, timeout=180)
    except subprocess.TimeoutExpired:
        return False, "verification timed out after 180s"
    if result.returncode != 0:
        last_lines = "\n".join(result.stderr.strip().splitlines()[-10:])
        return False, f"exit {result.returncode}; last stderr lines:\n{last_lines}"
    out_files = list(out_dir.glob("verify*"))
    if not out_files:
        return False, f"generate-image.py returned 0 but no file in {out_dir}"
    return True, f"verified via {VERIFY_MODEL}, output: {out_files[0]}"


def main() -> None:
    ap = argparse.ArgumentParser(
        description=__doc__.split("\n\n")[0],
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    ap.add_argument("--name", required=True, help="provider toml stem (lowercase, [a-z0-9._-])")
    ap.add_argument("--base-url", required=True)
    ap.add_argument("--api-key", help="api key (omit and pass via stdin instead)")
    ap.add_argument("--key-stdin", action="store_true", help="read api key from stdin")
    ap.add_argument("--auth-style", choices=["google", "bearer"], required=True)
    ap.add_argument("--docs-url", default="", help="docs URL (optional but recommended)")
    ap.add_argument("--display", default="", help="display name (default: derived from --name)")
    ap.add_argument("--models", default="",
                    help=f"comma-separated model IDs. Default for Gemini-shape: "
                         f"{','.join(DEFAULT_MODELS_GEMINI)}")
    ap.add_argument("--force", action="store_true",
                    help="overwrite existing toml of same name")
    ap.add_argument("--no-verify", action="store_true",
                    help="skip round-trip verification (NOT recommended)")
    args = ap.parse_args()

    if not VALID_NAME_RE.match(args.name):
        die(f"invalid --name {args.name!r}: must match {VALID_NAME_RE.pattern}")
    if args.name == "google" and not args.force:
        die("--name google is reserved for the official Google template; "
            "pick a different name (e.g. google-myaccount) or pass --force")

    api_key = args.api_key
    if args.key_stdin:
        api_key = sys.stdin.read().strip()
    if not api_key:
        die("no api key supplied (use --api-key or --key-stdin)")
    if not args.base_url.startswith(("http://", "https://")):
        die(f"--base-url {args.base_url!r} doesn't look like an http(s) URL")

    PROVIDER_DIR.mkdir(parents=True, exist_ok=True)
    toml_path = PROVIDER_DIR / f"{args.name}.toml"
    if toml_path.exists() and not args.force:
        die(f"{toml_path} already exists. Pass --force to overwrite, "
            f"or pick a different --name.")

    models = [m.strip() for m in args.models.split(",") if m.strip()] \
        or DEFAULT_MODELS_GEMINI
    display = args.display or args.name
    toml_path.write_text(render_toml(
        name=args.name,
        display=display,
        base_url=args.base_url.rstrip("/"),
        api_key=api_key,
        auth_style=args.auth_style,
        docs_url=args.docs_url,
        models=models,
    ))
    # Lock down so the file is at least owner-only
    try:
        toml_path.chmod(0o600)
    except Exception:
        pass
    print(f"→ wrote {toml_path}", file=sys.stderr)

    if args.no_verify:
        print(f"⚠ verification skipped (--no-verify). verified=false in the toml.",
              file=sys.stderr)
        print(str(toml_path))
        return

    print(f"→ verifying via {VERIFY_MODEL}... (~$0.04, ~10s)", file=sys.stderr)
    ok, msg = verify_round_trip(args.name)
    if not ok:
        print(f"✗ verification FAILED: {msg}", file=sys.stderr)
        print(f"  toml left at {toml_path} with verified=false", file=sys.stderr)
        print(f"  fix the offending field(s) and re-run register-provider.py", file=sys.stderr)
        sys.exit(2)

    mark_verified(toml_path)
    print(f"✓ {msg}", file=sys.stderr)
    print(f"✓ {toml_path} marked verified=true", file=sys.stderr)
    print(str(toml_path))


if __name__ == "__main__":
    main()
